### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BShapr#1]
When run through Jalv, I don't get any output;

![rose_2019-04-17-23:23:29](https://user-images.githubusercontent.com/108225/56324804-ddaae100-6167-11e9-8ca6-515ab8660e34.png)

When run in Carla, there is no waveform or audio output;

![rose_2019-04-17-23:19:10](https://user-images.githubusercontent.com/108225/56324631-4cd40580-6167-11e9-9d22-9b11d4ff64cd.png)

**Comment by sjaehn** [comment]
Did you switch on Jack transport? The (actual version of this) plugin needs the host speed information (which is 0 if Jack transport is stopped, and usually is 1 on playing) as the plugin also handles reverse playing (speed < 0).

I didn't try Carla yet, so I'll have a look at it.

**Comment by sjaehn** [comment]
Just tested it in Carla. Behaviour as you described if Jack transport is OFF. Everything fine if ON. At least on my system. Please tell me, if the problems persist after switch ON Jack transport.

**Comment by sjaehn** [comment]
Input but no output:
i) not connected to host in and out (not the case here)
ii) Audio in or audio out or both not marked (not the case here) or
iii) Shaper line at zero level. Take care, start and end nodes are at 0.0 by default (TODO set to 1.0) and can be moved by dragging the nodes. Take care part ii, if you drag everything else than a node (or a handle) you will drag the sheet of the shape. Thus, you move the 0.0 (and the 1.0, ...) line but the nodes still stick on this line.
iv) Or maybe it's a bug.

**Comment by mxmilkb** [comment]
Aah, two things;

JACK Transport was 'on' (provided by Carla) but not running (playing).

Also, in Carla, I had to click the Ableton Link radio button before the waveform started appearing. I can unclick Ableton Link and the waveform is working.

This latter problem is not consistent.

Shaper line - I can drag the whole thing up and down at once, yes? Is that looking right in the screenshot?

**Comment by mxmilkiib** [comment]
Aah, two things;

JACK Transport was 'on' (provided by Carla) but not running (playing).

Also, in Carla, I had to click the Ableton Link radio button before the waveform started appearing. I can unclick Ableton Link and the waveform is working.

This latter problem is not consistent.

Shaper line - I can drag the whole thing up and down at once, yes? Is that looking right in the screenshot?

(BTW, I can keep dragging the shaper line up and up and up and up, and it takes the same time to drag down again.)

Also, when I have Ableton Live ticked, the waveform starts to draw very weirdly, until I untick it.

But still no output :/

**Comment by sjaehn** [comment]
Do not try to drag the line as this will only move the underlying sheet. Instead drag the nodes. You will und understand this behavior if you add an additional node before. Mark one oft the node symbols and then click in the desired position oft the sheet.

**Comment by mxmilkiib** [comment]
That did it :) I dragged the left node up and I got audio. Unfortunately, after a couple of minutes, the plugin and Carla UIs became unresponsive, so I had to kill them, though the audio had continued.

**Comment by sjaehn** [comment]
I made the following changes to make it more intuitive:

- Preselect point node tool in 3ca15a792cd2430c2bfba14a053b63f2b55b3383
- Display values on grid in shaper in 3ca15a792cd2430c2bfba14a053b63f2b55b3383
- Target-dependent default end nodes in 3ca15a792cd2430c2bfba14a053b63f2b55b3383
- Target-dependent default shaper scaling in 3ca15a792cd2430c2bfba14a053b63f2b55b3383 

Unresponsiveness in Carla is a second point. I'll try to reproduce it to see what happens and why.

**Comment by sjaehn** [comment]
I tried to reproduce the unresponsiveness bug in Carla, but I couldn't observe it. So I can't tell you what happened and can't fix it. I know that GUI response in Carla is sometimes a bit lagging, but this doesn't seem to be the cause here (although I suspected it and therefore run Carla with a dozen of B.Shapr instances - without problems).

Please let me know, if the problems persist or anybody else observe it too.

**Comment by sjaehn** [comment]
Although I couldn't reproduce this problem, I suspect the level monitor may be the cause. The level monitor (in contrast to all other widgets) is directly called by incoming notifications from the DSP and not scheduled to B.Widgets event handler. I will change this when I will work on v0.3.

**Comment by sjaehn** [comment]
Fixed in d647e7fdc428ed634b3f34288fdf427752d61d30 , if the level monitor caused this problem. If not, please let me know.
