### ISSUE TITLE
resetting in Carla when GUI re-opens

### ISSUE THREAD

**Issue by SquidRoe** [sjaehn/BShapr#11]
When I close the B.Shapr window in Carla, it continues working as expected. But when I re-open it (ie, to change some settings), all of the nodes seem to become inactive. I can grab any node in each scene, and that will "wake up" the curve, but until I do that, the effects are all on but in the initial state.

My envelopes are still there - I can see them - but I need to "wiggle" a node to get the computer to see the envelope. This is true from both "Rack" and "Patchbay" (in Carla).

Everything seems normal in Ardour.

I'm using Carla 2.0.90 in Debian 9.

**Comment by sjaehn** [comment]
Thank you for reporting. I just uploaded some major updates of the underlying widget TK and I hope this will fix your problem. At least I couldn't reproduce this bug with this new version.

**Comment by sjaehn** [comment]
I just red on linuxmusicians.com that the described problem still persists. Let me ask you if I correctly understand you to theoretically reproduce this bug in Carla:

1) You used a single sheet (Shape1) and you created an envelope shape by placing some nodes using the default method (Level) or an other method.
2) Everything works fine at this point. You can see the nodes, the envelope, and you can hear the effect.
3) If you switch off the B.Shapr GUI in Carla (so the plugin is only shown as a rack element in Carla rack or a symbol with its connections in Carla patchbay). You can still hear the effect as expected.
4) If you switch on the B.Shapr GUI again, you can't see the envelope and the nodes. And you can't hear the effect. Everything seem to be lost.
5) If you change something in this "lost" shape ("wiggle"), everything gets restored. Now you can see the envelope and the nodes again. And you can hear the effect again.

There are lots of possibilities that may cause this problem:
* It looks like Carla creates a new instance of the GUI. This can be OK. But might also be a result of a GUI crash on GUI close.
* Or the GUI fails to inform the plugin that the GUI is online again.
* Or the plugin fails to receive this message.
* Or the plugin fails to send all shapes on GUI on.
* Or the GUI fails to handle the shape data.
* Or Carla itself fails to call the LV2 retrieve function.

It would be nice to know if there is an error message in the logs (logs tab or console). Also an important information would be if the dials (smooth, dry/wet) are correctly restored or not.

**Comment by SquidRoe** [comment]
Thanks for continuing with this. I was hoping to hear if other people had the same problem or it's just me, but no one has commented.

I'm not at my computer now - I'll post any crash reports when I get back - but what you say (1-3) is basically correct. #4 is a little different. I can SEE the nodes, see the envelope, but the plugin ignores them. The effect is still on; nothing is lost, but I need to "wiggle" a node to make the plug-in "see" the envelope again - when I wiggle one node, the entire envelope is active again.

This is the case for each of the four shapes. If I'm using four shapes, I need to wiggle a node in each shape.

I know the effect is still on, because if the effect is Low Pass Filter, I hear the sound switch from the tempo-sync'd envelopes (while the GUI is closed) to just a constant low pass filter (when I re-open it).

I believe all the dials are unaffected (it seems to only be the envelope), but I'll confirm later.

**Comment by sjaehn** [comment]
Thanks for the detailed information. Now I was able to reproduce it. There are no errors in the logs. And it happens for all shapes unless the method "Level" (= default) is selected. Now I know what I'm looking for.

**Comment by sjaehn** [comment]
The same happens  if I save & load a carla session. With the difference that now also the GUI envelope and nodes for all shapes are lost. Unless method "Level" is selected.

**Comment by sjaehn** [comment]
I found the cause. The plugin will run without any problems unless the host communicate the plugin and GUI provided data at a very unlucky point of time. Then a change of the method will result in a change of the default shape (only contains default end nodes for the respective method) in the GUI and this is communicated back to the plugin whilst the GUI receives the right shape data submitted by the plugin before. This is the case for the use in Carla.

This problem will automatically disappear if I take my hands on the TODO "relative shape nodes". Then there will be no need to change the default end nodes upon change of the method that caused the problem. However, this will be a bigger workaround.

**Comment by sjaehn** [comment]
TODO "relative shape nodes" is just finished. Fixes also solve also your reported "sound effect lost on GUI on bug" in Carla.

As the new version uses a total different way to store nodes, there may be host-dependent problems to correctly recover data from older versions of this plugin (incompatibilities). However, I couldn't see such problems in Carla and Ardour.

**Comment by SquidRoe** [comment]
Excellent! First quick test (with all four shapes) on my system in Carla and Ardour, perfect success. Thank you!
