### ISSUE TITLE
0.11 unable to build

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BShapr#19]
Hi! When building 0.11 for Arch Linux I ran into the following:

```
Build BShapr.lv2 DSP...Build BShapr.lv2 GUI...Build BShapr.lv2 (CV version) DSP...Build BShapr.lv2 (CV version) GUI... done.
 done.
 done.
g++: error: BShapr.lv2/tmp/*.o: No such file or directory
make: *** [makefile:175: BShaprGUI-cv.so] Error 1
```

It seems as if although [the directories are seemingly created](https://github.com/sjaehn/BShapr/blob/4106c92bf1d92b7967b2224c227d2279f46a7b93/makefile#L171-L175) (and they exist while compiling!) they are removed before line 175 is executed.

I somehow fixed this by making the `mkdir` calls verbose... I don't quite understand why and I don't think that is the correct solution.
I believe this might be a concurrency issue. Do you usually build this with only one core?

The removal of the build files should ideally be done in a separate `clean` target, as it leads to these rather weird to debug issues during build otherwise.

**Comment by sjaehn** [comment]
Thanks to mention. But it has a different cause. The error you get and the ugly console output looks like the result of **parallel** `make` using the `-j` parameter (although I couldn't reproduce it on my system (Ubuntu focal)). If everything runs fine (non-parallel), the output should be:
```
Build BShapr.lv2 DSP... done.
Build BShapr.lv2 GUI... done.
Build BShapr.lv2 (CV version) DSP... done.
Build BShapr.lv2 (CV version) GUI... done.
```

Parallel `make` is not intended for the B.Music plugins. `make` (without `-j`) in Arch-based Manjaro went fine without errors. But parallel `make` is not excluded yet. I'll add `.NOTPARALLEL:` to the end of the makefile to prevent parallel `make`. You can try this if you want.

Anyway, I'll take over your idea with the tmp_cv path as this is cleaner/safer :-).
