### ISSUE TITLE
No input with Ardour

### ISSUE THREAD

**Issue by tavasti** [sjaehn/BShapr#2]
When I try this in Ardour (or Mixbus), it looks like there is no input received. 

Jack transport is running, because error message about stopped jack transport disappears as soon as I put Ardour running. 

Pin connections in Ardour look normal (2x audio in, 2x out)

In input graph there is peaks when adjusting curve, and cracks heard on output, but real input is missing.

**Comment by sjaehn** [comment]
Thank you for your information. I can reproduce this problem and I'll take a closer look on it.

**Comment by sjaehn** [comment]
Yes, found it. Some LV2 hosts use the same memory address for input and output. Like Ardour. The old version of this plugin cleared the output first and therefore accidentally cleared the input too in Ardour. This bug in now fixed in 9ca434d7aba67cd0733ff91b11e5160e9464d1b0.

**Comment by tavasti** [comment]
Verified, works!
