### ISSUE TITLE
clicks and pops when jack transport resets

### ISSUE THREAD

**Issue by ghost** [sjaehn/BShapr#21]
even if you don't adjust any settings in the plugin, it'll produce a popping noise every time the jack transport resets to 0 (e.g., when you're playing a track clip in a loop)

tested with the latest versions of bshapr and qtractor

**Comment by sjaehn** [comment]
Partially related to https://github.com/sjaehn/BShapr/issues/22 . I think this is a result of a changed sequence position and thus hard-changed parameters. The plugin has got a smooth parameter to prevent these hard changes. I'll check if smoothing also works if jumped back to position 0.

May I ask you with which effect the clicks and pops become audible?

**Comment by ghost** [comment]
i left it at the default, which is "level"

**Comment by sjaehn** [comment]
Although I couldn't confirm it by listening (using Ardour*), I can confirm it by looking into the code. The smooth option only prevents clicks produced by "stairs" in the user-made shape. But it doesn't prevent clicks by position jumps. I'll fix this. But this might be a bigger change and will take some time.

*I think that the DAW should provide an option (set on default) to fade in/ out when playback starts or ends or when the position is changed (e. g., in a loop). If not, the click will already be produced by the DAW. Ardour has got a "fader" plugin placed on default to each track.

**Comment by sjaehn** [comment]
Smoothing behaviour is now changed in 8e1af80f1b638eacb1aac4e73dc501292c35a110 . This means that the shape isn't smoothed anymore (to prevent hard stairs) but the shape triggers a fader. This again means that a jump in position doesn't mean a hard jump in a value. As it gets faded.

Also fixed the issue #22 in 38f4f68fda1b1bb26f50040ea5f18a4f8970cf91. I hope both fixes solve the problem in qtactor.

**Comment by ghost** [comment]
this fixed it! thx
