### ISSUE TITLE
plugin output is muted when jack transport stops

### ISSUE THREAD

**Issue by ghost** [sjaehn/BShapr#22]
if you add the plugin to something without having the daw playback enabled, everything going into that plugin is muted. the plugin only produces sound when the playback is enabled

**Comment by sjaehn** [comment]
Right. The transport depends on the host bar / beat information if the sequence size unit is set to "Bars" or "Beats". Therefore no output. But it should work if you set the unit to "Seconds" as the transport is always running then (if the plugin is connected).

The only thing to think about is if the output signal should be muted or not. Maybe it also works with unmuted output and constant parameters. But I'm not sure about it. I've to do some tests.

**Comment by sjaehn** [comment]
Requested feature implemented in 38f4f68fda1b1bb26f50040ea5f18a4f8970cf91 . It seems to work without any problems. If the transport is stopped, then only the shape transport will be stopped and the latest shape value will be used. Only exception: the MIDI-triggered mode. I'll look if it's possible to do the same with the other B.Music plugins. Thanks to mention this problem.
