### ISSUE TITLE
Shape tab doesn't update all parameters

### ISSUE THREAD

**Issue by muziker** [sjaehn/BShapr#23]
With multiple tabs of Shapes, clicking on a tab should change the bottom left drop down menu to reflect the effect that is in use at the moment, but b.shapr does not do that moment.

Also with 3 tabs open, selecting tab 2 then back to tab 1, doesn't cause tab 1 to highlight, though the left/right scroll pane is updated to show the tab's control points. Similarly the effects box on the bottom left isn't updated to show the correct effect.

**Comment by muziker** [comment]
That was in carla. 

In Reaper, the tabs work fine, but the dry/wet doesn't stick to it's updated value.

**Comment by sjaehn** [comment]
Sorry for the late response. I tried to reproduce in Carla, but I can't. Everything works fine for me. Do you use the latest version of B.Shapr? And please keep in mind that clicking on a tab results in switching to the respective tab, whereas clicking on the left/right arrows results in moving the shape content and all its parameters. And this works fine in my case. Can anyone else reproduce the one or the other behaviour?

**Comment by muziker** [comment]
Oh ! Looks like i might have misunderstood the intent of the arrows !
