### ISSUE TITLE
[SOLVED] Tempo Sync Issues

### ISSUE THREAD

**Issue by whanake-music** [sjaehn/BShapr#24]
B.Shapr usually works as expected, but if it's placed on any track in Ardour that isn't a MIDI track, it seems to operate at 120 BPM regardless of what Ardour's tempo is set to. Might I suggest either fixing this tempo sync issue, or just adding an option to set the tempo in B.Shapr independently from its host? I get the same issues in Zrythm, so it definitely seems like a plugin issue rather than a host issue.

**Comment by sjaehn** [comment]
Ardour audio tracks come along without any information about time and sync. But Ardour provides a way to add MIDI (and thus all the time and beats information) to an audio track. This is the way to go.

**Comment by ultra-vi-olet** [comment]
Oh I see! Awesome, thanks for the tip. For anyone who sees this in the future: to add MIDI tempo information to an audio track, click on the audio track's input menu in the mixer view, then click 'Add MIDI Port' near the bottom of the dropdown menu. Instantly fixed the issue for me.
