### ISSUE TITLE
In Ardour max used env len is one bar

### ISSUE THREAD

**Issue by tavasti** [sjaehn/BShapr#3]
When using BShapr in Ardour 5.12.0, input will jump back to beginning at end of the bar. Regardless of used unit or lenght, at end of bar pattern is started over.

**Comment by sjaehn** [comment]
Thank you for your information. I can confirm this bug. I'll look at it.

**Comment by sjaehn** [comment]
Indeed, time_bar information wasn't caught from host and thus remained at 0 even if the next bar was reached. Now fixed in 6c7e2e53813f29dc64ed2677aa57ff36f3513eb3.

**Comment by tavasti** [comment]
Verified, works
