### ISSUE TITLE
Only Shape 1 has effect in Ardour

### ISSUE THREAD

**Issue by tavasti** [sjaehn/BShapr#4]
I can't get shape 2 or shape 3 to do anything in Ardour. This can be 'stupid user' thing also...

**Comment by sjaehn** [comment]
Did you connect (select) "audio" (or another input) in the input section above the shape editor? And did you connect (select) "audio" in output section below the shape editor?

About the input output logic:
1) You can select an input for each of the four shapers. This can be a stereo input signal (audio), a constant value or the output of a previous shaper. If non is selected, you dont get any input for the respective shaper.
2) The output can be used internally (deselected "audio") or sent to audio out (selected "audio"). You can set audio out for more then one shaper, if you want.

**Comment by tavasti** [comment]
This is 'stupid user' thing. No output selected.

**Comment by sjaehn** [comment]
Anyway thanks for your feedback. This shows, the plugin isn't very intuitive. I'm thinking about changing the default settings (audio in -> shape1 -> shape2 -> shape3 -> shape4 -> audio out). But this would cost CPU load by default as all four shapes need to be iterated sample by sample. So, the uses has to delete connections to save CPU time. Other option would be to show a message if an active shape is idle.

**Comment by tavasti** [comment]
I think showing message might be good option.

**Comment by sjaehn** [comment]
Messages are added in 85fd06f44abbb0e9c8825d0842cdfe12af61945d.

**Comment by tavasti** [comment]
Verified, works fine!
