### ISSUE TITLE
Odd ev->time.frames make B.Shapr crash in Ardour

### ISSUE THREAD

**Issue by sjaehn** [sjaehn/BShapr#6]
Dividing the control atom port to a control and a midi port resulted in a crash in Ardour. It turned out that the plugin received events with ev->time.frames out of the expected range.
 
ev->time.frames usually ranges between 0 and n_samples. For time_Position events in the control port usually ev->time.frames == 0. For GUI->DSP events (like notify_shapeEvent) ev->time.frames == n_samples .

[https://github.com/sjaehn/BShapr/blob/master/src/BShapr.cpp#L397](https://github.com/sjaehn/BShapr/blob/master/src/BShapr.cpp#L397)

![Bildschirmfoto vom 2019-10-26 21-54-08](https://user-images.githubusercontent.com/42939779/67625231-a36b7c00-f83b-11e9-98d4-0a51b40312d8.png).

But the midi port also receives time_Position, but with  ev->time.frames > n_samples.

[https://github.com/sjaehn/BShapr/blob/master/src/BShapr.cpp#L433](https://github.com/sjaehn/BShapr/blob/master/src/BShapr.cpp#L433)

![Bildschirmfoto von 2019-10-26 22-31-19](https://user-images.githubusercontent.com/42939779/67625591-6e155d00-f840-11e9-941a-ca3881bf2423.png)

The problem is fixed by skipping time_Position events from midi port.

**Comment by x42** [comment]
I highly recommend to only use a single Atom input, but if you must use two, the first one should be the one to receive MIDI input.

The 2nd port likely contains garbage (ardour connects it to a silent/scratch buffer).

**Comment by sjaehn** [comment]
Thank you. Your answer is the one I expected / was afraid of. I think port 2 is indeed the problem. At least ev->time.frames contains garbage. Roll back and try to get both, MIDI and time_Position in one atom input.

**Comment by SpotlightKid** [comment]
Carla also doesn't handle two atom ports correctly: https://github.com/falkTX/Carla/issues/915

**Comment by sjaehn** [comment]
Done in 9ec78e76b54ab2ac169160f5553dba688ab492dc
