### ISSUE TITLE
Grid is too dim

### ISSUE THREAD

**Issue by tavasti** [sjaehn/BShapr#8]
Grid (specally vertical grid) is so dim that with my eyesight & display I hardly can see it.

**Comment by sjaehn** [comment]
Is this ( ed00ffbba8dc597752224210377e0e39de24dd8a ) better ?

**Comment by tavasti** [comment]
It is better, but still on black area (above curve) it is nearly invisible.

**Comment by sjaehn** [comment]
Fascinating, I from my POV I observed the opposite. Weak contrast below the curve, good above.

**Comment by tavasti** [comment]
Oh, strange! 

Bit experimenting with colors, I think best way might be grow those dots / have more of them for vertical grid.

**Comment by sjaehn** [comment]
Grid point size just set to 2.0 in ec8905d007f1e7460ba9b0c4b1f3c644bd16ecd2 . If you want to play around, you can now set the size in https://github.com/sjaehn/BShapr/blob/master/src/definitions.hpp#L33 line 33. The point colors are defined in https://github.com/sjaehn/BShapr/blob/master/src/BShaprGUI.hpp#L184 line 184, first of the four quadruplets ({red, green, blue, alpha}).

Grid space is automatically calculated.

On my screen it now looks like heavy snowfall ;-).

**Comment by tavasti** [comment]
Ok, now it looks ok for me. And had also moderate snow fall today, that looked also ok :-)
